### ISSUE TITLE
missing constraintLayout id

### ISSUE THREAD

**Issue by tiro105** [googlecodelabs/constraint-layout#11]
please add id of ConstraintLayout in activity_main_start.xml
or I want in addition to the procedure in codeLabs.

**Comment by nageshs** [comment]
Sure but is this causing a problem?

**Comment by tiro105** [comment]
Thank you for your reply!

In conclusion it did not cause problems especially in AndroidStudio 2.3 Beta 1.

Before I tried, if I did not set constraintLayout id, when I operated according to the explanation of codeLab, behavior was wrong.
So I made this issue, but as I mentioned earlier, I do not have any problems so I will close it.

Thank you for answering!
