### ISSUE TITLE
constraint-layout dependencies error

### ISSUE THREAD

**Issue by twlkyao** [googlecodelabs/constraint-layout#15]
With the "constraint-layout:1.0.0-alpha2" the project cannot compile through, gives the output:

> Error:(22, 13) Failed to resolve: com.android.support.constraint:constraint-layout:1.0.0-alpha2
> <a href="install.m2.artifact">Install artifact and sync project</a><br><a href="openFile:C:/Users/steveqi/Desktop/constraint-layout-master/constraint-layout-start/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a> 

when change to "constraint-layout:1.0.0-alpha1" it worked.

**Comment by lvwenbo0107** [comment]
u should download it in sdk manager.

**Comment by Myth1** [comment]
u should click install artifact and sync project

**Comment by nageshs** [comment]
Please download the latest version of the constraint-layout dependency (as of today it's beta4)
