### ISSUE TITLE
ScrollView as Parent?

### ISSUE THREAD

**Issue by mantas84** [googlecodelabs/constraint-layout#18]
In example 
![image](https://cloud.githubusercontent.com/assets/11000895/22081736/71938e38-ddcd-11e6-86ea-815416fbb3e8.png)
everything looks good when using portrait orientation, but on landscape constraint-layout cuts off description textView.

**Comment by nageshs** [comment]
Actually you'd need a different layout for landscape and put it into layout-land. The objective of constraint-layout is not to provide a layout that works across config such as portrait/landscape changes.

**Comment by mantas84** [comment]
I understand that constraint-layout objective is to flatten layout structure, so nested Linear/Relative layouts could be replaced with one constraint-layout. But can constraint-layout flatten ScrollView or any other layout?
