### ISSUE TITLE
Rendering problems of the initial file

### ISSUE THREAD

**Issue by magdalenakubiak9** [googlecodelabs/constraint-layout#20]
Hello, 
the preview of the activity_main_done doesn't work on my Android Studio (version 2.2.3).
I have tried to change the library into `compile 'com.android.support.constraint:constraint-layout:1.0.0-beta4'` but it shows error in the xml file and when I upgrade to recommended version it changed the ConstraintLayout library in build.gradle back to `com.android.support.constraint:constraint-layout:1.0.0`.

I have tried Invalidate Caches and restarting the project.

Nothing worked. Can anybody help me?

Thanks in advance
Magda

**Comment by Akshar-Patel** [comment]
Same issue here.

**Comment by magdalenakubiak9** [comment]
I didn't solve the issue in my case. But clicking "Build the project" on the rendering problems message did :)

**Comment by nageshs** [comment]
Yes the Invalidate Caches/Restart should resolve the problem. let me know if the problem persists after that
