### ISSUE TITLE
Margin when gone doesn't work for last view in vertical chain

### ISSUE THREAD

**Issue by mehmedean** [googlecodelabs/constraint-layout#42]
I have three views chained together vertically. I assign a layout_goneMarginBottom value to the last item (id:tvStore). When I set its visibility to GONE, the bottom margin I assigned doesn't work.

```
<android.support.constraint.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="100dp">

        <TextView
            android:id="@+id/tvHeader"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            app:layout_constraintBottom_toTopOf="@+id/tvDescription"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintVertical_chainStyle="packed" />

        <TextView
            android:id="@+id/tvDescription"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            app:layout_constraintBottom_toTopOf="@+id/tvStore"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/tvHeader" />

        <TextView
            android:id="@+id/tvStore"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/tvDescription"
            app:layout_goneMarginBottom="30dp" />

</android.support.constraint.ConstraintLayout>
```

**Comment by vicobz** [comment]
I have the same issue

**Comment by EricRLewis** [comment]
Yup, same issue here. Work around by adding an extra 0dp view at the end of the chain

**Comment by islinker** [comment]
Little late to the game here, but I think the problem is related to which view you added "layout_goneMarginBottom" to. It is intended to be added to the view that will need to compensate for the missing view, in this case "tvDescription".

**Comment by rohan20** [comment]
@islinker You sir, are a genius 🥇 PS: It's never too late!

**Comment by mehmedean** [comment]
So "layout_goneMarginX" is "X margin when connected to a GONE widget" rather than "X margin when GONE", which means the attribute should be on the adjacent view. This is also apparent on the [related part](https://developer.android.com/reference/android/support/constraint/ConstraintLayout#GoneMargin) of the documentation.

@islinker Thank you for clarification.

**Comment by mehmedean** [comment]
So "layout_goneMarginX" is "X margin when connected to a GONE widget" rather than "X margin when GONE", which means the attribute should be on the adjacent view. This is also apparent on the title of the [related part](https://developer.android.com/reference/android/support/constraint/ConstraintLayout#GoneMargin) of the documentation.

@islinker Thank you for clarification.

**Comment by SohailZahidGit** [comment]
Issue solved by setting last (Bottom) view     `app:layout_constraintBottom_toBottomOf="parent"` if you removed bottom margin disappears why check this [thread](https://stackoverflow.com/questions/48082480/margintop-does-not-work-with-constraintlayout-and-wrap-content?rq=1).

**Comment by navyifanr** [comment]
But when I want to realize that just show "tvHeader" and keep marginBottom="30dp", how to write it? Add more `app:layout_goneMarginBottom="30dp"` in "tvHeader"? But when just show "tvHeader" and "tvStore" not work,  there is more the margin between "tvHeader" and "tvStore"
