### ISSUE TITLE
constraint-layout:1.0.0-alpha2 not resolved

### ISSUE THREAD

**Issue by austenlux** [googlecodelabs/constraint-layout#6]
When adding:
`compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha2'`
to the build.gradle file, you will receive an error stating that the dependency could not be resolved.
The `1.0.0-alpha2` version of the dependency doesn't appear to exist on jcenter. `1.0.0-alpha1` works fine though.

**Comment by mss725626** [comment]
This depend on the version of dependency you have on your system. In my case I have 1.0.0-alpha3.
