### ISSUE TITLE
Gradle Sync button doesn't seem to exist

### ISSUE THREAD

**Issue by pdunwin** [googlecodelabs/constraint-layout#8]
The instructions in Step 3 say click the Gradle sync button. I don't find this button in version 2.2 and I'm told it doesn't exist in that version.

I'm able to bring in the code and look at the constraint view, though it doesn't seem to look right.

**Comment by jiachenning** [comment]
I meet the same issue. found I import it from the dir `constraint-layout`. as step 3 say I should import from `constraint-layout-start`. Then it works.

**Comment by nageshs** [comment]
Thanks @jiachenning! closing this issue.
